import { arrayGivenArrayLike } from "./_internal/arrayGivenArrayLike";
import { arrayGivenPattern } from "./_internal/arrayGivenPattern";
import { arrayIsEmptyOrNull } from "./_internal/arrayIsEmptyOrNull";
import { arrayWithEqualSizeGroups } from "./_internal/arrayWithEqualSizeGroups";
import { arrayWithLeftShift } from "./_internal/arrayWithLeftShift";
import { arrayWithMovedValue } from "./_internal/arrayWithMovedValue";
import { arrayWithOrderFromValue } from "./_internal/arrayWithOrderFromValue";
import { arrayWithoutDuplicateValues } from "./_internal/arrayWithoutDuplicateValues";
import { arrayWithoutValue } from "./_internal/arrayWithoutValue";
import { arrayWithPageSubset } from "./_internal/arrayWithPageSubset";
import { arrayWithReversedOrder } from "./_internal/arrayWithReversedOrder";
import { arrayWithRightShift } from "./_internal/arrayWithRightShift";
import { arrayWithValue } from "./_internal/arrayWithValue";
import { numberArrayGivenRange } from "./_internal/numberArrayGivenRange";
import { optionalIndexOfFirstMatchGivenArray } from "./_internal/optionalIndexOfFirstMatchGivenArray";
import { optionalLastValueGivenArray } from "./_internal/optionalLastValueGivenArray";
import { optionalNthValueGivenArray } from "./_internal/optionalNthValueGivenArray";
import { optionalRandomValueGivenArray } from "./_internal/optionalRandomValueGivenArray";
import { valueGivenArray } from "./_internal/valueGivenArray";

export class ArrayUtil {
  static arrayGivenArrayLike = arrayGivenArrayLike;
  static arrayGivenPattern = arrayGivenPattern;
  static arrayIsEmptyOrNull = arrayIsEmptyOrNull;
  static arrayWithEqualSizeGroups = arrayWithEqualSizeGroups;
  static arrayWithLeftShift = arrayWithLeftShift;
  static arrayWithOrderFromValue = arrayWithOrderFromValue;
  static arrayWithoutDuplicateValues = arrayWithoutDuplicateValues;
  static arrayWithoutValue = arrayWithoutValue;
  static arrayWithMovedValue = arrayWithMovedValue;
  static arrayWithPageSubset = arrayWithPageSubset;
  static arrayWithReversedOrder = arrayWithReversedOrder;
  static arrayWithRightShift = arrayWithRightShift;
  static arrayWithValue = arrayWithValue;
  static numberArrayGivenRange = numberArrayGivenRange;
  static optionalIndexOfFirstMatchGivenArray = optionalIndexOfFirstMatchGivenArray;
  static optionalLastValueGivenArray = optionalLastValueGivenArray;
  static optionalNthValueGivenArray = optionalNthValueGivenArray;
  static optionalRandomValueGivenArray = optionalRandomValueGivenArray;
  static valueGivenArray = valueGivenArray;
}
